### ISSUE TITLE
Can't reach configuration page

### ISSUE THREAD

**Issue by ohiohiker** [ZeSlammy/iSpindHub#1]
I have installed on a D1 mini and I can see the hub on my local network but when I try to access it via the IP address, all I get is a screen with "Hello World".  I have also tried on the iSpindHub wifi and get the same result.  I think I am missing something.

**Comment by antoinespace** [comment]
Hello, when I do a reset with the Wemos button I enter the "iSpindHubConfig" configuration network.

**Comment by ZeSlammy** [comment]
Hello
Make sure you load both the Software part and the Data Part.
I'll update the readme.

**Comment by ohiohiker** [comment]
What address do you upload the data part to when flashing using an ESP flasher?

**Comment by ZeSlammy** [comment]
I'm using eagle.flash.4m3m.ld

/* Flash Split for 4M chips */
/* sketch @0x40200000 (~1019KB) (1044464B) */
/* empty  @0x402FEFF0 (~4KB) (4112B) */
/* spiffs @0x40300000 (~3048KB) (3121152B) */
/* eeprom @0x405FB000 (4KB) */
/* rfcal  @0x405FC000 (4KB) */
/* wifi   @0x405FD000 (12KB) */

I'm doing everything in VS, I will update the ReadMe with both solutions.

**Comment by ohiohiker** [comment]
Thanks, I tried doing it in VS Code and was still working out some errors I kept getting.  My coding is rusty, haven't done much in 15 years or so.

**Comment by popo42bis** [comment]
J'ai le même problème et je suis un gros noob. Pourriez-vous m'aider s'il vous plaît ? Encore merci d'avance

**Comment by ZeSlammy** [comment]
All
I added 3 Firmwares (1.4/1.7/2 inches) to BrewFlasher (Get it : https://github.com/thorrak/brewflasher/releases ) so use this to flash and test.
