### ISSUE TITLE
Allow the user to change the SSID name

### ISSUE THREAD

**Issue by MatthBou** [ZeSlammy/iSpindHub#5]
Salut Nicolas,

Just a small feature request ;)

It would be nice if the user could change the name of the wifi.
In the case of having two iSpinHub in the same room, this would allow the user to choose which hub the iSpindel sends data to.
Thank you in advance!

**Comment by ZeSlammy** [comment]
Hello @MatthBou 
It's done in the version delivered on GitHub.
I will push releases as soon as possible.

**Comment by MatthBou** [comment]
> Hello @MatthBou It's done in the version delivered on GitHub. I will push releases as soon as possible.

Hi Nicolas, I just flashed from the github, but I can't find the option anywhere...
Where should I look?

**Comment by ZeSlammy** [comment]
Mmmh weird. You flashed both the firmware and the filesystem ?
Have you force refreshed the web pages ?
Should be under settings, "name of iSpindHub". I will take screenshots

**Comment by ZeSlammy** [comment]
Well .... I hadn't updated the GitHub with a working version .... It's done now :( Sorry.

**Comment by MatthBou** [comment]
> Well .... I hadn't updated the GitHub with a working version .... It's done now :( Sorry.

Nothing has changed...
I flashed again from the github and from brewflasher (2inche v0.0.1 6-Alpha). I don't see the option...

**Comment by MatthBou** [comment]
I made a mistake the option is there, problem solved
